CREATE USER @user WITH LOGIN NOSUPERUSER INHERIT CREATEDB NOCREATEROLE NOREPLICATION PASSWORD @pass;

GRANT CONNECT ON DATABASE "look-inna-book" TO @user;
GRANT USAGE ON SCHEMA @schema TO @user;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA @schema TO @user;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA @schema TO @user;